src/Entity/Formation.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FormationRepository")
 */
class Formation
{
    use TimestampableEntity;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $titre;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $duree;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $reference;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $pedagogie;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $publicVise;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $prerequis;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lieu;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $cpf;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $photo;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $lien;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $facebook;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $trameARealiser;

    /**
     * @ORM\Column(type="boolean", nullable=true)
     */
    private $trameValiderIperia;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Formateur", inversedBy="formations")
     */
    private $formateurs;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $numero_cpf;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $theme;

    /**
     * @ORM\Column(type="text", length=65535, nullable=true)
     */
    private $descriptif;

    /**
     * @ORM\OneToMany(targetEntity="App\Entity\SessionFormation", mappedBy="formation")
     */
    private $sessionFormations;

    public function __construct()
    {
        $this->formateurs = new ArrayCollection();
        $this->sessionFormations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitre(): ?string
    {
        return $this->titre;
    }

    public function setTitre(string $titre): self
    {
        $this->titre = $titre;

        return $this;
    }

    public function getDuree(): ?int
    {
        return $this->duree;
    }

    public function setDuree(?int $duree): self
    {
        $this->duree = $duree;

        return $this;
    }

    public function getReference(): ?string
    {
        return $this->reference;
    }

    public function setReference(string $reference): self
    {
        $this->reference = $reference;

        return $this;
    }

    public function getPedagogie(): ?string
    {
        return $this->pedagogie;
    }

    public function setPedagogie(string $pedagogie): self
    {
        $this->pedagogie = $pedagogie;

        return $this;
    }

    public function getPublicVise(): ?string
    {
        return $this->publicVise;
    }

    public function setPublicVise(string $publicVise): self
    {
        $this->publicVise = $publicVise;

        return $this;
    }

    public function setformateurs(string $formateurs): self
    {
        $this->formateurs = $formateurs;

        return $this;
    }

    public function getPrerequis(): ?string
    {
        return $this->prerequis;
    }

    public function setPrerequis(string $prerequis): self
    {
        $this->prerequis = $prerequis;

        return $this;
    }

    public function getLieu(): ?string
    {
        return $this->lieu;
    }

    public function setLieu(string $lieu): self
    {
        $this->lieu = $lieu;

        return $this;
    }

    public function getCpf(): ?bool
    {
        return $this->cpf;
    }

    public function setCpf(?bool $cpf): self
    {
        $this->cpf = $cpf;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->photo;
    }

    public function setPhoto(?string $photo): self
    {
        $this->photo = $photo;

        return $this;
    }

    public function getLien(): ?string
    {
        return $this->lien;
    }

    public function setLien(?string $lien): self
    {
        $this->lien = $lien;

        return $this;
    }

    public function getFacebook(): ?string
    {
        return $this->facebook;
    }

    public function setFacebook(?string $facebook): self
    {
        $this->facebook = $facebook;

        return $this;
    }

    public function getTheme(): ?string
    {
        return $this->theme;
    }

    public function setTheme(?string $theme): self
    {
        $this->theme = $theme;

        return $this;
    }

    public function getTrameARealiser(): ?bool
    {
        return $this->trameARealiser;
    }

    public function setTrameARealiser(?bool $trameARealiser): self
    {
        $this->trameARealiser = $trameARealiser;

        return $this;
    }

    public function getTrameValiderIperia(): ?bool
    {
        return $this->trameValiderIperia;
    }

    public function setTrameValiderIperia(?bool $trameValiderIperia): self
    {
        $this->trameValiderIperia = $trameValiderIperia;

        return $this;
    }

    /**
     * @return Collection|Formateur[]
     */
    public function getformateurs(): Collection
    {
        return $this->formateurs;
    }

    public function addFormateur(Formateur $formateur): self
    {
        if (!$this->formateurs->contains($formateur)) {
            $this->formateurs[] = $formateur;
        }

        return $this;
    }

    public function removeFormateur(Formateur $formateur): self
    {
        if ($this->formateurs->contains($formateur)) {
            $this->formateurs->removeElement($formateur);
        }

        return $this;
    }

    public function getNumeroCpf(): ?int
    {
        return $this->numero_cpf;
    }

    public function setNumeroCpf(?int $numero_cpf): self
    {
        $this->numero_cpf = $numero_cpf;

        return $this;
    }

    public function __toString()
    {
        return $this->getTitre();
    }

    public function getDescriptif(): ?string
    {
        return $this->descriptif;
    }

    public function setDescriptif(?string $descriptif): self
    {
        $this->descriptif = $descriptif;

        return $this;
    }

    /**
     * @return Collection|SessionFormation[]
     */
    public function getSessionFormations(): Collection
    {
        return $this->sessionFormations;
    }

    public function addSessionFormation(SessionFormation $sessionFormation): self
    {
        if (!$this->sessionFormations->contains($sessionFormation)) {
            $this->sessionFormations[] = $sessionFormation;
            $sessionFormation->setFormation($this);
        }

        return $this;
    }

    public function removeSessionFormation(SessionFormation $sessionFormation): self
    {
        if ($this->sessionFormations->contains($sessionFormation)) {
            $this->sessionFormations->removeElement($sessionFormation);
            // set the owning side to null (unless already changed)
            if ($sessionFormation->getFormation() === $this) {
                $sessionFormation->setFormation(null);
            }
        }

        return $this;
    }

}

src/Form/FormationType.php
<?php

namespace App\Form;

use App\Entity\Formation;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FormationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('titre')
            ->add('duree')
            ->add('reference')
            ->add('pedagogie')
            ->add('publicVise')
            ->add('prerequis')
            ->add('lieu')
            ->add('cpf')
            ->add('photo')
            ->add('lien')
            ->add('facebook')
            ->add('trameARealiser')
            ->add('trameValiderIperia')
            ->add('numero_cpf')
            ->add('theme')
            ->add('descriptif')
            ->add('createdAt')
            ->add('updatedAt')
            ->add('formateurs')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Formation::class,
        ]);
    }
}

src/Controller/FormationController.php
<?php

namespace App\Controller;

use App\Entity\Formation;
use App\Form\FormationType;
use App\Repository\FormationRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/formation")
 */
class FormationController extends AbstractController
{
    /**
     * @Route("/", name="formation_index", methods={"GET"})
     */
    public function index(FormationRepository $formationRepository): Response
    {
        return $this->render('formation/index.html.twig', [
            'formations' => $formationRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="formation_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $formation = new Formation();
        $form = $this->createForm(FormationType::class, $formation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($formation);
            $entityManager->flush();

            return $this->redirectToRoute('formation_index');
        }

        return $this->render('formation/new.html.twig', [
            'formation' => $formation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="formation_show", methods={"GET"})
     */
    public function show(Formation $formation): Response
    {
        return $this->render('formation/show.html.twig', [
            'formation' => $formation,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="formation_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Formation $formation): Response
    {
        $form = $this->createForm(FormationType::class, $formation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('formation_index', [
                'id' => $formation->getId(),
            ]);
        }

        return $this->render('formation/edit.html.twig', [
            'formation' => $formation,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="formation_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Formation $formation): Response
    {
        if ($this->isCsrfTokenValid('delete'.$formation->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($formation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('formation_index');
    }
}

templates/formation/_delete_form.html.twig
<form method="post" action="{{ path('formation_delete', {'id': formation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ formation.id) }}">
    <button class="btn">Delete</button>
</form>

templates/formation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Formation{% endblock %}

{% block body %}
    <h1>Edit Formation</h1>

    {{ include('formation/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('formation_index') }}">back to list</a>

    {{ include('formation/_delete_form.html.twig') }}
{% endblock %}

templates/formation/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formation index{% endblock %}

{% block body %}
    <h1>Formation index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Titre</th>
                <th>Duree</th>
                <th>Reference</th>
                <th>Pedagogie</th>
                <th>PublicVise</th>
                <th>Prerequis</th>
                <th>Lieu</th>
                <th>Cpf</th>
                <th>Photo</th>
                <th>Lien</th>
                <th>Facebook</th>
                <th>TrameARealiser</th>
                <th>TrameValiderIperia</th>
                <th>Numero_cpf</th>
                <th>Theme</th>
                <th>Descriptif</th>
                <th>CreatedAt</th>
                <th>UpdatedAt</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for formation in formations %}
            <tr>
                <td>{{ formation.id }}</td>
                <td>{{ formation.titre }}</td>
                <td>{{ formation.duree }}</td>
                <td>{{ formation.reference }}</td>
                <td>{{ formation.pedagogie }}</td>
                <td>{{ formation.publicVise }}</td>
                <td>{{ formation.prerequis }}</td>
                <td>{{ formation.lieu }}</td>
                <td>{{ formation.cpf ? 'Yes' : 'No' }}</td>
                <td>{{ formation.photo }}</td>
                <td>{{ formation.lien }}</td>
                <td>{{ formation.facebook }}</td>
                <td>{{ formation.trameARealiser ? 'Yes' : 'No' }}</td>
                <td>{{ formation.trameValiderIperia ? 'Yes' : 'No' }}</td>
                <td>{{ formation.numeroCpf }}</td>
                <td>{{ formation.theme }}</td>
                <td>{{ formation.descriptif }}</td>
                <td>{{ formation.createdAt ? formation.createdAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ formation.updatedAt ? formation.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('formation_show', {'id': formation.id}) }}">show</a>
                    <a href="{{ path('formation_edit', {'id': formation.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="20">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('formation_new') }}">Create new</a>
{% endblock %}

templates/formation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Formation{% endblock %}

{% block body %}
    <h1>Create new Formation</h1>

    {{ include('formation/_form.html.twig') }}

    <a href="{{ path('formation_index') }}">back to list</a>
{% endblock %}

templates/formation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formation{% endblock %}

{% block body %}
    <h1>Formation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ formation.id }}</td>
            </tr>
            <tr>
                <th>Titre</th>
                <td>{{ formation.titre }}</td>
            </tr>
            <tr>
                <th>Duree</th>
                <td>{{ formation.duree }}</td>
            </tr>
            <tr>
                <th>Reference</th>
                <td>{{ formation.reference }}</td>
            </tr>
            <tr>
                <th>Pedagogie</th>
                <td>{{ formation.pedagogie }}</td>
            </tr>
            <tr>
                <th>PublicVise</th>
                <td>{{ formation.publicVise }}</td>
            </tr>
            <tr>
                <th>Prerequis</th>
                <td>{{ formation.prerequis }}</td>
            </tr>
            <tr>
                <th>Lieu</th>
                <td>{{ formation.lieu }}</td>
            </tr>
            <tr>
                <th>Cpf</th>
                <td>{{ formation.cpf ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Photo</th>
                <td>{{ formation.photo }}</td>
            </tr>
            <tr>
                <th>Lien</th>
                <td>{{ formation.lien }}</td>
            </tr>
            <tr>
                <th>Facebook</th>
                <td>{{ formation.facebook }}</td>
            </tr>
            <tr>
                <th>TrameARealiser</th>
                <td>{{ formation.trameARealiser ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>TrameValiderIperia</th>
                <td>{{ formation.trameValiderIperia ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Numero_cpf</th>
                <td>{{ formation.numeroCpf }}</td>
            </tr>
            <tr>
                <th>Theme</th>
                <td>{{ formation.theme }}</td>
            </tr>
            <tr>
                <th>Descriptif</th>
                <td>{{ formation.descriptif }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ formation.createdAt ? formation.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>UpdatedAt</th>
                <td>{{ formation.updatedAt ? formation.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('formation_index') }}">back to list</a>

    <a href="{{ path('formation_edit', {'id': formation.id}) }}">edit</a>

    {{ include('formation/_delete_form.html.twig') }}
{% endblock %}