src/Entity/Formateur.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Timestampable\Traits\TimestampableEntity;

/**
 * @ORM\Entity(repositoryClass="App\Repository\FormateurRepository")
 */
class Formateur
{
    use TimestampableEntity;

    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

    /**
     * @ORM\Column(type="date")
     */
    private $date_de_naissance;

    /**
     * @ORM\Column(type="string", length=255, unique=true)
     */
    private $mail;

    /**
     * @ORM\Column(type="integer")
     */
    private $telephone;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $meilleur_diplome;

    /**
     * @ORM\Column(type="boolean")
     */
    private $salarie;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $fonction_actuelle;

    /**
     * @ORM\Column(type="text")
     */
    private $domaine_expertise;

    /**
     * @ORM\Column(type="text")
     */
    private $mode_acquisition;

    /**
     * @ORM\Column(type="array")
     */
    private $type_formations = [];

    /**
     * @ORM\Column(type="array")
     */
    private $zone_execution = [];

    /**
     * @ORM\Column(type="array")
     */
    private $formation_iperia = [];

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Formation", mappedBy="formateurs")
     */
    private $formations;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\SessionFormation", mappedBy="formateurs")
     */
    private $sessionFormations;

    public function __construct()
    {
        $this->formations = new ArrayCollection();
        $this->sessionFormations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getDateDeNaissance(): ?\DateTimeInterface
    {
        return $this->date_de_naissance;
    }

    public function setDateDeNaissance(\DateTimeInterface $date_de_naissance): self
    {
        $this->date_de_naissance = $date_de_naissance;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getTelephone(): ?int
    {
        return $this->telephone;
    }

    public function setTelephone(int $telephone): self
    {
        $this->telephone = $telephone;

        return $this;
    }

    public function getMeilleurDiplome(): ?string
    {
        return $this->meilleur_diplome;
    }

    public function setMeilleurDiplome(string $meilleur_diplome): self
    {
        $this->meilleur_diplome = $meilleur_diplome;

        return $this;
    }

    public function getSalarie(): ?bool
    {
        return $this->salarie;
    }

    public function setSalarie(bool $salarie): self
    {
        $this->salarie = $salarie;

        return $this;
    }

    public function getFonctionActuelle(): ?string
    {
        return $this->fonction_actuelle;
    }

    public function setFonctionActuelle(string $fonction_actuelle): self
    {
        $this->fonction_actuelle = $fonction_actuelle;

        return $this;
    }

    public function getDomaineExpertise(): ?string
    {
        return $this->domaine_expertise;
    }

    public function setDomaineExpertise(string $domaine_expertise): self
    {
        $this->domaine_expertise = $domaine_expertise;

        return $this;
    }

    public function getModeAcquisition(): ?string
    {
        return $this->mode_acquisition;
    }

    public function setModeAcquisition(string $mode_acquisition): self
    {
        $this->mode_acquisition = $mode_acquisition;

        return $this;
    }

    public function getTypeFormations(): ?array
    {
        return $this->type_formations;
    }

    public function setTypeFormations(array $type_formations): self
    {
        $this->type_formations = $type_formations;

        return $this;
    }

    public function getZoneExecution(): ?array
    {
        return $this->zone_execution;
    }

    public function setZoneExecution(array $zone_execution): self
    {
        $this->zone_execution = $zone_execution;

        return $this;
    }

    public function getFormationIperia(): ?array
    {
        return $this->formation_iperia;
    }

    public function setFormationIperia(array $formation_iperia): self
    {
        $this->formation_iperia = $formation_iperia;

        return $this;
    }

    public function __toString()
    {
        return $this->getNom()." ".$this->getPrenom();
    }

    /**
     * @return Collection|Formation[]
     */
    public function getFormations(): Collection
    {
        return $this->formations;
    }

    public function addFormation(Formation $formation): self
    {
        if (!$this->formations->contains($formation)) {
            $this->formations[] = $formation;
            $formation->addFormateur($this);
        }

        return $this;
    }

    public function removeFormation(Formation $formation): self
    {
        if ($this->formations->contains($formation)) {
            $this->formations->removeElement($formation);
            $formation->removeFormateur($this);
        }

        return $this;
    }

    /**
     * @return Collection|SessionFormation[]
     */
    public function getSessionFormations(): Collection
    {
        return $this->sessionFormations;
    }

    public function addSessionFormation(SessionFormation $sessionFormation): self
    {
        if (!$this->sessionFormations->contains($sessionFormation)) {
            $this->sessionFormations[] = $sessionFormation;
            $sessionFormation->addFormateur($this);
        }

        return $this;
    }

    public function removeSessionFormation(SessionFormation $sessionFormation): self
    {
        if ($this->sessionFormations->contains($sessionFormation)) {
            $this->sessionFormations->removeElement($sessionFormation);
            $sessionFormation->removeFormateur($this);
        }

        return $this;
    }
}

src/Form/FormateurType.php
<?php

namespace App\Form;

use App\Entity\Formateur;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\CollectionType;
use Symfony\Component\Form\Extension\Core\Type\NumberType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class FormateurType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom')
            ->add('prenom')
            ->add('date_de_naissance')
            ->add('mail')
            ->add('telephone')
            ->add('meilleur_diplome')
            ->add('salarie')
            ->add('fonction_actuelle')
            ->add('domaine_expertise')
            ->add('mode_acquisition')
            ->add('type_formations', CollectionType::class)
            ->add('zone_execution', CollectionType::class, [
                'entry_type' => NumberType::class
            ])
            ->add('formation_iperia', CollectionType::class, [
                'entry_type' => NumberType::class
            ])
            ->add('createdAt')
            ->add('updatedAt')
            ->add('formations')
            ->add('sessionFormations')
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Formateur::class,
        ]);
    }
}

src/Controller/FormateurController.php
<?php

namespace App\Controller;

use App\Entity\Formateur;
use App\Form\FormateurType;
use App\Repository\FormateurRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/formateur")
 */
class FormateurController extends AbstractController
{
    /**
     * @Route("/", name="formateur_index", methods={"GET"})
     * @param FormateurRepository $formateurRepository
     * @return Response
     */
    public function index(FormateurRepository $formateurRepository): Response
    {
        return $this->render('formateur/index.html.twig', [
            'formateurs' => $formateurRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="formateur_new", methods={"GET","POST"})
     * @param Request $request
     * @return Response
     */
    public function new(Request $request): Response
    {
        $formateur = new Formateur();
        $form = $this->createForm(FormateurType::class, $formateur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($formateur);
            $entityManager->flush();

            return $this->redirectToRoute('formateur_index');
        }

        return $this->render('formateur/new.html.twig', [
            'formateur' => $formateur,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="formateur_show", methods={"GET"})
     * @param Formateur $formateur
     * @return Response
     */
    public function show(Formateur $formateur): Response
    {
        return $this->render('formateur/show.html.twig', [
            'formateur' => $formateur,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="formateur_edit", methods={"GET","POST"})
     * @param Request $request
     * @param Formateur $formateur
     * @return Response
     */
    public function edit(Request $request, Formateur $formateur): Response
    {
        $form = $this->createForm(FormateurType::class, $formateur);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('formateur_index', [
                'id' => $formateur->getId(),
            ]);
        }

        return $this->render('formateur/edit.html.twig', [
            'formateur' => $formateur,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="formateur_delete", methods={"DELETE"})
     * @param Request $request
     * @param Formateur $formateur
     * @return Response
     */
    public function delete(Request $request, Formateur $formateur): Response
    {
        if ($this->isCsrfTokenValid('delete'.$formateur->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($formateur);
            $entityManager->flush();
        }

        return $this->redirectToRoute('formateur_index');
    }
}

templates/formateur/_delete_form.html.twig
<form method="post" action="{{ path('formateur_delete', {'id': formateur.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ formateur.id) }}">
    <button class="btn">Delete</button>
</form>

templates/formateur/_form.html.twig
{{ form_start(form) }}
{{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/formateur/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Formateur{% endblock %}

{% block body %}
    <h1>Edit Formateur</h1>

    {{ include('formateur/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('formateur_index') }}">back to list</a>

    {{ include('formateur/_delete_form.html.twig') }}
{% endblock %}

templates/formateur/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Formateur{% endblock %}

{% block body %}
    <h1>Create new Formateur</h1>

    {{ include('formateur/_form.html.twig') }}

    <a href="{{ path('formateur_index') }}">back to list</a>
{% endblock %}

templates/formateur/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Formateur{% endblock %}

{% block body %}
    <h1>Formateur</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ formateur.id }}</td>
            </tr>
            <tr>
                <th>Nom</th>
                <td>{{ formateur.nom }}</td>
            </tr>
            <tr>
                <th>Prenom</th>
                <td>{{ formateur.prenom }}</td>
            </tr>
            <tr>
                <th>Date_de_naissance</th>
                <td>{{ formateur.dateDeNaissance ? formateur.dateDeNaissance|date('Y-m-d') : '' }}</td>
            </tr>
            <tr>
                <th>Mail</th>
                <td>{{ formateur.mail }}</td>
            </tr>
            <tr>
                <th>Telephone</th>
                <td>{{ formateur.telephone }}</td>
            </tr>
            <tr>
                <th>Meilleur_diplome</th>
                <td>{{ formateur.meilleurDiplome }}</td>
            </tr>
            <tr>
                <th>Salarie</th>
                <td>{{ formateur.salarie ? 'Yes' : 'No' }}</td>
            </tr>
            <tr>
                <th>Fonction_actuelle</th>
                <td>{{ formateur.fonctionActuelle }}</td>
            </tr>
            <tr>
                <th>Domaine_expertise</th>
                <td>{{ formateur.domaineExpertise }}</td>
            </tr>
            <tr>
                <th>Mode_acquisition</th>
                <td>{{ formateur.modeAcquisition }}</td>
            </tr>
            <tr>
                <th>Type_formations</th>
                <td>{{ formateur.typeFormations ? formateur.typeFormations|join(', ') : '' }}</td>
            </tr>
            <tr>
                <th>Zone_execution</th>
                <td>{{ formateur.zoneExecution ? formateur.zoneExecution|join(', ') : '' }}</td>
            </tr>
            <tr>
                <th>Formation_iperia</th>
                <td>{{ formateur.formationIperia ? formateur.formationIperia|join(', ') : '' }}</td>
            </tr>
            <tr>
                <th>CreatedAt</th>
                <td>{{ formateur.createdAt ? formateur.createdAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>UpdatedAt</th>
                <td>{{ formateur.updatedAt ? formateur.updatedAt|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('formateur_index') }}">back to list</a>

    <a href="{{ path('formateur_edit', {'id': formateur.id}) }}">edit</a>

    {{ include('formateur/_delete_form.html.twig') }}
{% endblock %}